name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ${{matrix.os}}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        include:
          - build: linux
            os: ubuntu-latest
            rust: beta
            target: x86_64-unknown-linux-musl
            cross: false
          - build: macos
            os: macos-latest
            rust: beta
            target: x86_64-apple-darwin
            cross: false
          - build: windows
            os: windows-latest
            rust: beta
            target: x86_64-pc-windows-msvc
            cross: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: Swatinem/rust-cache@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true
          default: true
          components: rustfmt, clippy

      - name: Ubuntu AppArmor fix
        if: ${{ matrix.os == 'ubuntu-latest' }}
        # Ubuntu >= 23 has AppArmor enabled by default, which breaks Chrome.
        # See https://github.com/puppeteer/puppeteer/issues/12818 "No usable sandbox!"
        # this is taken from the solution used in Puppeteer's CI: https://github.com/puppeteer/puppeteer/pull/13196
        # The alternative is to pin Ubuntu 22 or to use aa-exec to disable AppArmor for commands that need Puppeteer.
        # This is also suggested by Chromium https://chromium.googlesource.com/chromium/src/+/main/docs/security/apparmor-userns-restrictions.md
        run: |
          echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns
        shell: bash

      - name: Build Lib
        working-directory: ./toolproof
        run: cargo build

      - name: Test Lib
        working-directory: ./toolproof
        run: cargo test

      - uses: browser-actions/setup-chrome@v1

      - name: Test CLI
        working-directory: ./toolproof
        # toolproof tests itself when run
        run: cargo run -- --placeholders toolproof_path="$(pwd)/../target/debug/toolproof" -c 1 --timeout 60
